{
  "openapi": "3.0.0",
  "info": {
    "title": "Auth-App",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://127.0.0.1:3000"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "auth"
    },
    {
      "name": "users"
    }
  ],
  "paths": {
    "/api/v1/auth/signup/": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "SignUp",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "firstname": "Shadrach",
                  "lastname": "Oforkansi",
                  "email": "oforkansi.shadrach@outlook.com",
                  "password": "test1234"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "58"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3a-YFnB1eJaxUebMxQh/vDiu0rKBgw\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 13:13:34 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "User created successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/verify/{token}": {
      "get": {
        "tags": [
          "auth"
        ],
        "summary": "Account Verify",
        "parameters": [
          {
            "name": "token",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true,
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWYxNWFiNWY1OWYxMGQzODJiZTk4ZCIsImVtYWlsIjoib2ZvcmthbnNpLnNoYWRyYWNoQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1OTgzNTgxOSwiZXhwIjoxNjU5ODM5NDE5fQ.mdGLSR3VwQFABdzzhYxfoSiTVNpzriNOIgcipPDPcFY"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "59"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3b-wiz/dTndDxB9wKQgwdSgQpuYoz0\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 01:36:13 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "User verified successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/login/": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "oforkansi.shadrach@gmail.com",
                  "password": "test12345"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "314"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"13a-UGqsEa5rh8f/KwjUTokO/avi9ow\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 01:38:40 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "User logged in successfully",
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWYxNWFiNWY1OWYxMGQzODJiZTk4ZCIsImVtYWlsIjoib2ZvcmthbnNpLnNoYWRyYWNoQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1OTgzNjMyMCwiZXhwIjoxNjU5ODM5OTIwfQ.D6T8eXYO8y_zlPstHRj5dbnnHbrL5RrCzO_VcwquoNQ"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/password_reset/": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Forgot Password",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "oforkansi.shadrach@gmail.com"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "71"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"47-iXsX54ZRbGGgbnvKCbCV0Gxp5uI\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 01:41:51 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "Password reset link sent to your email"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/{token}/": {
      "post": {
        "tags": [
          "auth"
        ],
        "summary": "Confirm Password Reset",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "password": "test12345"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "token",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true,
            "example": "confirm_password_reset/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZWYxNWFiNWY1OWYxMGQzODJiZTk4ZCIsImVtYWlsIjoib2ZvcmthbnNpLnNoYWRyYWNoQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1OTgzNjUxMSwiZXhwIjoxNjU5ODQwMTExfQ.xHS6Ugn9KlgEIN8vWb7KZL0LNypqcKgrCnbptKvva6M"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "60"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3c-WlWDlqR3lD8e0KPzC+xDFKWfWiY\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 01:43:46 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "Password reset successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/auth/logout/": {
      "get": {
        "tags": [
          "auth"
        ],
        "summary": "Logout",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "61"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3d-dOpBAULxHtr7+aIW1TeWWSR6pVo\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 02:43:29 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "User logged out successfully"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/": {
      "get": {
        "tags": [
          "users"
        ],
        "summary": "List Users",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "397"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"18d-sKi93+Hya1zWky4nJoQA321n0wQ\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 02:55:04 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "Users retrieved successfully",
                  "data": [
                    {
                      "_id": "62ef15ab5f59f10d382be98d",
                      "firstname": "Shadrach",
                      "lastname": "Oforkansi",
                      "email": "oforkansi.shadrach@gmail.com",
                      "password": "$2b$10$KLKphbeznrB.af.EJVj2sOQTH4hKIhtwz/qHEzkr9YR.qk1WXmF.e",
                      "role": "admin",
                      "is_verified": true,
                      "createdAt": "2022-08-07T01:30:19.297Z",
                      "updatedAt": "2022-08-07T02:40:25.063Z",
                      "is_logged_in": false
                    }
                  ]
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "42"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"2a-ntivdrzEK6EgIlxbB2kQrOsT45Y\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 02:54:17 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "fail",
                  "message": "Not an admin"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/{id}/": {
      "delete": {
        "tags": [
          "users"
        ],
        "summary": "Delete User",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true,
            "example": "62ef373ae9f48dac5dc9eb9b/"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "58"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"3a-WIRP18LrlipyzL/lm3MsmTsH7cI\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 03:54:45 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "User deleted successfully"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "52"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"34-lnGc6n2N4NO/qWMBWksgV1Bge3Q\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 03:52:04 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "fail",
                  "message": "Not enough permissions"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Update User",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "firstname": "john",
                  "lastname": "doe"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true,
            "example": "62ef15ab5f59f10d382be98d"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "381"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"17d-HFchpHISemUf6rNMF5Fb1cpQ64Y\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 13:24:07 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "User updated successfully",
                  "data": {
                    "_id": "62ef15ab5f59f10d382be98d",
                    "firstname": "john",
                    "lastname": "doe",
                    "email": "oforkansi.shadrach@gmail.com",
                    "password": "$2b$10$KLKphbeznrB.af.EJVj2sOQTH4hKIhtwz/qHEzkr9YR.qk1WXmF.e",
                    "role": "admin",
                    "is_verified": true,
                    "createdAt": "2022-08-07T01:30:19.297Z",
                    "updatedAt": "2022-08-07T13:24:07.450Z",
                    "is_logged_in": true
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/users/{id}/role": {
      "put": {
        "tags": [
          "users"
        ],
        "summary": "Assign User Role",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "role": "staff"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "schema": {
              "type": "string"
            },
            "required": true,
            "example": "62efba7dffa062e85de46f6f"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "Express"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json; charset=utf-8"
                }
              },
              "Content-Length": {
                "schema": {
                  "type": "integer",
                  "example": "400"
                }
              },
              "ETag": {
                "schema": {
                  "type": "string",
                  "example": "W/\"190-4Gk+3WmeVYqgCb1DjxL3y1VwTzY\""
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Sun, 07 Aug 2022 13:17:11 GMT"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "keep-alive"
                }
              },
              "Keep-Alive": {
                "schema": {
                  "type": "string",
                  "example": "timeout=5"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "status": "success",
                  "message": "User role updated successfully",
                  "data": {
                    "_id": "62efba7dffa062e85de46f6f",
                    "firstname": "Shadrach",
                    "lastname": "Oforkansi",
                    "email": "oforkansi.shadrach@outlook.com",
                    "password": "$2b$10$0LOrF7DQpusDYKdGMv8AbeSqWlcwcHQMRT42IZJFPRhErois/yKkK",
                    "role": "staff",
                    "is_verified": false,
                    "is_logged_in": false,
                    "createdAt": "2022-08-07T13:13:33.975Z",
                    "updatedAt": "2022-08-07T13:17:11.622Z"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}